apiVersion: v1
kind: Namespace
metadata:
  name: external
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-vm
  namespace: external
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-vm
  namespace: external
spec:
  hosts:
  - external-vm.dwayne-eks-dev.dev.twistio.io
  location: MESH_INTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  workloadSelector:
    labels:
      app: external-vm
