apiVersion: networking.istio.io/v1alpha3
kind: WorkloadGroup
metadata:
  name: external-vm-$INST_ITER
  namespace: external
spec:
  metadata:
    labels:
      app: external-vm
  template:
    serviceAccount: external-vm
    network: ""
  probe:
    periodSeconds: 5
    initialDelaySeconds: 1
    httpGet:
      port: 80
      path: /get
