aspen-mesh-controlplane:
  clusterId: youthful-ferret
  userAuth:
    type: none

aspen-mesh-secure-ingress:
  enabled: false
  externalDnsEnabled: true
  lets-encrypt-email: dwayne@aspenmesh.io

external-dns:
  txtOwnerId: youthful-ferret

global:
  proxy:
    logLevel: info
    accessLogFile: "/dev/null"
  imagePullSecrets:
  - aspen-mesh-pull-secret
  - aspenmesh-istio-private-pr-pull-secret
  tracer:
    zipkin:
      # address is the Host:Port for reporting trace data in zipkin format. If
      # not specified, will default to zipkin service (port 9411) in the same
      # namespace as the other istio components.
      address: aspen-mesh-jaeger-collector.istio-system:9411
  enableEccCertificates: true

#meshConfig:
#  pathNormalization:
#    normalization: DECODE_AND_MERGE_SLASHES

citadel:
  enabled: true

jaeger:
  enabled: false
  cassandra:
    persistence:
      # This setting could cause upgrade errors if modified between deployments
      # of Aspen Mesh. If you see errors that the StatefulSet cannot be patched
      # due to updates to forbidden fields, you will have to delete the
      # "istio-cassandra" StatefulSet resource before performing an upgrade.
      size: 10Gi
  schema:
    annotations:
      helm.sh/hook: post-install,post-upgrade
      helm.sh/hook-delete-policy: before-hook-creation
      helm.sh/hook-weight: "0"

pilot:
  traceSampling: "1.0"

aspen-mesh-event-storage:
  resources:
    requests: null
    limits: null
