cni:
  cniBinDir: /var/lib/cni/bin
  cniConfDir: /etc/cni/multus/net.d
  cniConfFileName: istio-cni.conf

  excludeNamespaces:
  - istio-system
  - kube-node-lease
  - kube-public
  - kube-system
  - openshift
  - openshift-apiserver
  - openshift-apiserver-operator
  - openshift-authentication
  - openshift-authentication-operator
  - openshift-cloud-credential-operator
  - openshift-cluster-machine-approver
  - openshift-cluster-node-tuning-operator
  - openshift-cluster-samples-operator
  - openshift-cluster-storage-operator
  - openshift-cluster-version
  - openshift-config
  - openshift-config-managed
  - openshift-console
  - openshift-console-operator
  - openshift-controller-manager
  - openshift-controller-manager-operator
  - openshift-dns
  - openshift-dns-operator
  - openshift-etcd
  - openshift-image-registry
  - openshift-infra
  - openshift-ingress
  - openshift-ingress-operator
  - openshift-insights
  - openshift-kni-infra
  - openshift-kube-apiserver
  - openshift-kube-apiserver-operator
  - openshift-kube-controller-manager
  - openshift-kube-controller-manager-operator
  - openshift-kube-scheduler
  - openshift-kube-scheduler-operator
  - openshift-machine-api
  - openshift-machine-config-operator
  - openshift-marketplace
  - openshift-monitoring
  - openshift-multus
  - openshift-network-operator
  - openshift-node
  - openshift-openstack-infra
  - openshift-operator-lifecycle-manager
  - openshift-operators
  - openshift-sdn
  - openshift-service-ca
  - openshift-service-ca-operator
  - openshift-service-catalog-apiserver-operator
  - openshift-service-catalog-controller-manager-operator

  chained: false

  components:
    cni:
      namespace: kube-system

global:
  certificateCustomFields: false

  # generated certificates will use signature algorithm
  # ECDSA with a P-256 curve; for this to work, an ECDSA P-256 certificate must
  # be loaded in as the root CA certificate
  enableEccCertificates: false
