postsubmits:
- name: test-postsubmit
  decorate: true
  spec:
    containers:
    - image: alpine
      command: ["/bin/printenv"]
presubmits:
- name: test-presubmit
  decorate: true
  always_run: true
  skip_report: true
  spec:
    containers:
    - image: alpine
      command: ["/bin/printenv"]
