external-dns:
  txtOwnerId: dwayne-cluster2

global:
  multiCluster:
    # Should be set to the name of the cluster this installation will run in.
    # This is required for sidecar injection to properly label proxies.
    clusterName: "cluster2"
  network: network2

gateways:
  istio-ingressgateway:
    labels:
      topology.istio.io/network: network2
    env:
      ISTIO_META_REQUESTED_NETWORK_VIEW: "network2"
