apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: analysis-emulator
  namespace: analysis-emulator
spec:
  selector:
    matchLabels:
      app: packet-inspector-1-analysis-emulator
  endpoints:
  - port: http-admin
    path: /prommetrics
