apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  # Use the following command to find the IP range in use by Docker
  #   docker network inspect -f '{{.IPAM.Config}}' kind
  - 172.18.0.250-172.18.0.254
