analysis:
  # mode is either `normal` or `benchmark`. `benchmark` does not write capture
  # files and tracks unique requests
  mode: benchmark
#  processingDelay: 5ms
#  replicas: 10

serviceMonitor:
  enabled: true
  interval: 5s
