apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "http-server.fullname" . }}
  labels:
    {{- include "http-server.labels" . | nindent 4 }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ include "http-server.fullname" . }}
  http:
  - route:
    - destination:
        host: {{ include "http-server.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.port }}
